apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
spec:
  secretName: frontend-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.domain | quote }}
  issuerRef:
    name: letsencrypt-http01-issuer 
    kind: ClusterIssuer
    group: cert-manager.io
